one_letter = {'00C': 'C', '01W': 'X', '02K': 'A', '02L': 'N', '03Y': 'C', '04U': 'P', '04V': 'P', '05N': 'P', '07O': 'C',
      '08P': 'C', '0A0': 'D', '0A1': 'Y', '0A2': 'K', '0A8': 'C', '0AA': 'V', '0AB': 'V', '0AC': 'G', '0AD': 'G',
      '0AF': 'W', '0AG': 'L', '0AH': 'S', '0AK': 'D', '0AM': 'A', '0AP': 'C', '0AR': 'R', '0AU': 'U', '0AV': 'A',
      '0BN': 'F', '0C ': 'C', '0CS': 'A', '0DA': 'A', '0DC': 'C', '0DG': 'G', '0DT': 'T', '0E5': 'T', '0EA': 'Y',
      '0FL': 'A', '0G ': 'G', '0NC': 'A', '0PR': 'Y', '0SP': 'A', '0U ': 'U', '0WZ': 'Y', '0Y8': 'P', '0YG': 'X',
      '10C': 'C', '125': 'U', '126': 'U', '127': 'U', '128': 'N', '12A': 'A', '143': 'C', '175': 'X', '193': 'X',
      '1AP': 'A', '1IP': 'N', '1MA': 'A', '1MG': 'G', '1OP': 'Y', '1PA': 'F', '1PI': 'A', '1PR': 'N', '1SC': 'C',
      '1TQ': 'W', '1TY': 'Y', '1X6': 'S', '200': 'F', '23F': 'F', '23S': 'X', '26B': 'T', '2AD': 'X', '2AG': 'A',
      '2AO': 'X', '2AR': 'A', '2AS': 'X', '2AT': 'T', '2AU': 'U', '2BD': 'I', '2BT': 'T', '2BU': 'A', '2CO': 'C',
      '2DA': 'A', '2DF': 'N', '2DM': 'N', '2DO': 'X', '2DT': 'T', '2EG': 'G', '2FE': 'N', '2FI': 'N', '2FM': 'M',
      '2GT': 'T', '2HF': 'H', '2KK': 'K', '2KP': 'K', '2LU': 'L', '2MA': 'A', '2MG': 'G', '2ML': 'L', '2MR': 'R',
      '2MT': 'P', '2MU': 'U', '2NT': 'T', '2OM': 'U', '2OR': 'R', '2OT': 'T', '2PI': 'X', '2PR': 'G', '2QZ': 'T',
      '2R3': 'Y', '2SA': 'N', '2SI': 'X', '2ST': 'T', '2TL': 'T', '2TY': 'Y', '2VA': 'V', '2XA': 'C', '32S': 'X',
      '32T': 'X', '33X': 'A', '3AH': 'H', '3AR': 'X', '3CF': 'F', '3DA': 'A', '3DR': 'N', '3GA': 'A', '3GL': 'E',
      '3MD': 'D', '3ME': 'U', '3MY': 'Y', '3NF': 'Y', '3QN': 'K', '3TY': 'X', '3XH': 'G', '45A': 'A', '47C': 'C',
      '4AC': 'N', '4AW': 'W', '4BF': 'Y', '4CF': 'F', '4CY': 'M', '4DP': 'W', '4F3': 'X', '4FB': 'P', '4FW': 'W',
      '4GJ': 'C', '4HT': 'W', '4II': 'F', '4IN': 'W', '4MF': 'N', '4OC': 'C', '4PC': 'C', '4PD': 'C', '4PE': 'C',
      '4PH': 'F', '4SC': 'C', '4SU': 'U', '4TA': 'N', '4U7': 'A', '54C': 'W', '56A': 'H', '5AA': 'A', '5AB': 'A',
      '5AT': 'T', '5BU': 'U', '5CG': 'G', '5CM': 'C', '5CR': 'F', '5CS': 'C', '5CT': 'K', '5CW': 'W', '5FA': 'A',
      '5FC': 'C', '5FU': 'U', '5HP': 'E', '5HT': 'T', '5HU': 'U', '5IC': 'C', '5IT': 'T', '5IU': 'U', '5MC': 'C',
      '5MD': 'N', '5MU': 'U', '5NC': 'C', '5OW': 'K', '5PC': 'C', '5PG': 'G', '5PY': 'T', '5SE': 'U', '5SQ': 'X',
      '5VV': 'N', '5ZA': 'X', '64T': 'T', '68Z': 'G', '6BR': 'T', '6CL': 'K', '6CT': 'T', '6CW': 'W', '6DN': 'K',
      '6FK': 'G', '6G4': 'K', '6GL': 'A', '6HA': 'A', '6HC': 'C', '6HG': 'G', '6HN': 'K', '6HT': 'T', '6IA': 'A',
      '6MA': 'A', '6MC': 'A', '6MI': 'N', '6MT': 'A', '6MZ': 'A', '6OG': 'G', '6V1': 'C', '6WK': 'C', '70U': 'U',
      '73N': 'R', '73O': 'Y', '73P': 'K', '77Y': 'U', '7AT': 'A', '7DA': 'A', '7GU': 'G', '7JA': 'I', '7MG': 'G',
      '7N8': 'F', '7O5': 'A', '8AA': 'G', '8AG': 'G', '8AN': 'A', '8DT': 'U', '8FG': 'G', '8MG': 'G', '8OG': 'G',
      '8PY': 'G', '8RE': 'K', '8YN': 'C', '9DN': 'N', '9KP': 'K', '9NE': 'E', '9NF': 'F', '9NR': 'R', '9NV': 'V',
      'A  ': 'A', 'A1P': 'N', 'A23': 'A', 'A2L': 'A', 'A2M': 'A', 'A34': 'A', 'A35': 'A', 'A38': 'A', 'A39': 'A',
      'A3A': 'A', 'A3P': 'A', 'A40': 'A', 'A43': 'A', 'A44': 'A', 'A47': 'A', 'A5L': 'A', 'A5M': 'C', 'A5N': 'N',
      'A5O': 'A', 'A66': 'X', 'A7E': 'A', 'AA3': 'A', 'AA4': 'A', 'AAR': 'R', 'AB7': 'X', 'ABA': 'A', 'ABR': 'A',
      'ABS': 'A', 'ABT': 'N', 'ACB': 'D', 'ACL': 'R', 'AD2': 'A', 'ADD': 'X', 'ADX': 'N', 'AEA': 'C', 'AEI': 'D',
      'AET': 'A', 'AFA': 'N', 'AFF': 'N', 'AFG': 'G', 'AGM': 'R', 'AGT': 'C', 'AHB': 'N', 'AHH': 'X', 'AHO': 'A',
      'AHP': 'A', 'AHS': 'X', 'AHT': 'X', 'AIB': 'A', 'AKL': 'D', 'AKZ': 'D', 'ALA': 'A', 'ALC': 'A', 'ALM': 'A',
      'ALN': 'A', 'ALO': 'T', 'ALQ': 'X', 'ALS': 'A', 'ALT': 'A', 'ALV': 'A', 'ALY': 'K', 'AMD': 'A', 'AME': 'M',
      'AN8': 'A', 'AP7': 'A', 'APE': 'X', 'APH': 'A', 'API': 'K', 'APK': 'K', 'APM': 'X', 'APP': 'X', 'AR2': 'R',
      'AR4': 'E', 'AR7': 'R', 'ARG': 'R', 'ARM': 'R', 'ARO': 'R', 'ARV': 'X', 'AS ': 'A', 'AS2': 'D', 'AS9': 'X',
      'ASA': 'D', 'ASB': 'D', 'ASI': 'D', 'ASK': 'D', 'ASL': 'D', 'ASM': 'X', 'ASN': 'N', 'ASP': 'D', 'ASQ': 'D',
      'ASU': 'N', 'ASX': 'B', 'ATD': 'T', 'ATL': 'T', 'ATM': 'T', 'AVC': 'A', 'AVJ': 'H', 'AVN': 'X', 'AYA': 'A',
      'AYG': 'X', 'AZH': 'A', 'AZK': 'K', 'AZS': 'S', 'AZY': 'Y', 'B1F': 'F', 'B1P': 'N', 'B2A': 'A', 'B2C': 'X',
      'B2F': 'F', 'B2H': 'X', 'B2I': 'I', 'B2V': 'V', 'B3A': 'A', 'B3D': 'D', 'B3E': 'E', 'B3K': 'K', 'B3L': 'X',
      'B3M': 'X', 'B3Q': 'X', 'B3S': 'S', 'B3T': 'X', 'B3U': 'H', 'B3X': 'N', 'B3Y': 'Y', 'B8H': 'U', 'B8K': 'G',
      'B8Q': 'C', 'B8T': 'C', 'B8W': 'G', 'B9B': 'G', 'B9H': 'C', 'BB6': 'C', 'BB7': 'C', 'BB8': 'F', 'BB9': 'C',
      'BBC': 'C', 'BCS': 'C', 'BE2': 'X', 'BFD': 'D', 'BG1': 'S', 'BGH': 'G', 'BGM': 'G', 'BH2': 'D', 'BHD': 'D',
      'BIF': 'F', 'BIL': 'X', 'BIU': 'I', 'BJH': 'X', 'BL2': 'L', 'BLE': 'L', 'BLY': 'K', 'BMP': 'N', 'BMT': 'T',
      'BNN': 'F', 'BNO': 'X', 'BOE': 'T', 'BOR': 'R', 'BPE': 'C', 'BRU': 'U', 'BSE': 'S', 'BT5': 'N', 'BTA': 'L',
      'BTC': 'C', 'BTR': 'W', 'BUC': 'C', 'BUG': 'V', 'BVP': 'U', 'BWB': 'S', 'BXT': 'S', 'BZG': 'N', 'C  ': 'C',
      'C12': 'X', 'C1X': 'K', 'C22': 'A', 'C25': 'C', 'C2L': 'C', 'C2S': 'C', 'C31': 'C', 'C32': 'C', 'C34': 'C',
      'C36': 'C', 'C37': 'C', 'C38': 'C', 'C3Y': 'C', 'C42': 'C', 'C43': 'C', 'C45': 'C', 'C46': 'C', 'C49': 'C',
      'C4R': 'C', 'C4S': 'C', 'C5C': 'C', 'C66': 'X', 'C6C': 'C', 'C99': 'X', 'CAF': 'C', 'CAL': 'X', 'CAR': 'C',
      'CAS': 'C', 'CAV': 'X', 'CAY': 'C', 'CB2': 'C', 'CBR': 'C', 'CBV': 'C', 'CCC': 'C', 'CCL': 'K', 'CCS': 'C',
      'CCY': 'X', 'CDE': 'X', 'CDV': 'X', 'CDW': 'C', 'CEA': 'C', 'CFL': 'C', 'CFY': 'X', 'CG1': 'G', 'CG6': 'C',
      'CGA': 'E', 'CGU': 'E', 'CH ': 'C', 'CH6': 'X', 'CH7': 'X', 'CHF': 'X', 'CHG': 'X', 'CHP': 'G', 'CHS': 'X',
      'CIR': 'R', 'CJO': 'X', 'CLE': 'L', 'CLG': 'K', 'CLH': 'K', 'CLV': 'X', 'CM0': 'N', 'CME': 'C', 'CMH': 'C',
      'CML': 'C', 'CMR': 'C', 'CMT': 'C', 'CNU': 'U', 'CP1': 'C', 'CPC': 'X', 'CPI': 'X', 'CQR': 'X', 'CR0': 'X',
      'CR2': 'X', 'CR5': 'G', 'CR7': 'X', 'CR8': 'X', 'CRF': 'X', 'CRG': 'X', 'CRK': 'X', 'CRO': 'X', 'CRQ': 'X',
      'CRU': 'X', 'CRW': 'X', 'CRX': 'X', 'CS0': 'C', 'CS1': 'C', 'CS3': 'C', 'CS4': 'C', 'CS8': 'N', 'CSA': 'C',
      'CSB': 'C', 'CSD': 'C', 'CSE': 'C', 'CSF': 'C', 'CSH': 'X', 'CSJ': 'C', 'CSL': 'C', 'CSO': 'C', 'CSP': 'C',
      'CSR': 'C', 'CSS': 'C', 'CSU': 'C', 'CSW': 'C', 'CSX': 'C', 'CSY': 'X', 'CSZ': 'C', 'CTE': 'W', 'CTG': 'T',
      'CTH': 'T', 'CUC': 'X', 'CWR': 'S', 'CXM': 'M', 'CY0': 'C', 'CY1': 'C', 'CY3': 'C', 'CY4': 'C', 'CYA': 'C',
      'CYD': 'C', 'CYF': 'C', 'CYG': 'C', 'CYJ': 'K', 'CYM': 'C', 'CYQ': 'C', 'CYR': 'C', 'CYS': 'C', 'CZ2': 'C',
      'CZO': 'X', 'CZZ': 'C', 'D11': 'T', 'D1P': 'N', 'D3 ': 'N', 'D33': 'N', 'D3P': 'G', 'D3T': 'T', 'D4B': 'C',
      'D4M': 'T', 'D4P': 'X', 'DA ': 'A', 'DA2': 'R', 'DAB': 'A', 'DAH': 'F', 'DAL': 'A', 'DAR': 'R', 'DAS': 'D',
      'DBB': 'T', 'DBM': 'N', 'DBS': 'S', 'DBU': 'T', 'DBY': 'Y', 'DBZ': 'A', 'DC ': 'C', 'DC2': 'C', 'DCG': 'G',
      'DCI': 'X', 'DCL': 'X', 'DCT': 'C', 'DCY': 'C', 'DDE': 'H', 'DDG': 'G', 'DDN': 'U', 'DDX': 'N', 'DDZ': 'A',
      'DFC': 'C', 'DFG': 'G', 'DFI': 'X', 'DFO': 'X', 'DFT': 'N', 'DG ': 'G', 'DGH': 'G', 'DGI': 'G', 'DGL': 'E',
      'DGN': 'Q', 'DHA': 'S', 'DHI': 'H', 'DHL': 'X', 'DHN': 'V', 'DHP': 'X', 'DHU': 'U', 'DHV': 'V', 'DI ': 'I',
      'DI7': 'Y', 'DIL': 'I', 'DIR': 'R', 'DIV': 'V', 'DLE': 'L', 'DLS': 'K', 'DLY': 'K', 'DM0': 'K', 'DMH': 'N',
      'DMK': 'D', 'DMT': 'X', 'DN ': 'N', 'DNE': 'L', 'DNL': 'K', 'DNP': 'A', 'DNR': 'C', 'DNS': 'K', 'DOA': 'X',
      'DOC': 'C', 'DOH': 'D', 'DON': 'L', 'DPB': 'T', 'DPH': 'F', 'DPL': 'P', 'DPN': 'F', 'DPP': 'A', 'DPQ': 'Y',
      'DPR': 'P', 'DPY': 'N', 'DRM': 'U', 'DRP': 'N', 'DRT': 'T', 'DRZ': 'N', 'DSE': 'S', 'DSG': 'N', 'DSN': 'S',
      'DSP': 'D', 'DT ': 'T', 'DTH': 'T', 'DTR': 'W', 'DTY': 'Y', 'DU ': 'U', 'DVA': 'V', 'DXD': 'N', 'DXN': 'N',
      'DYA': 'D', 'DYG': 'X', 'DYJ': 'P', 'DYS': 'C', 'DZM': 'A', 'E  ': 'A', 'E1X': 'A', 'E3C': 'C', 'E6G': 'G',
      'E7G': 'G', 'E9C': 'Y', 'E9M': 'W', 'EAN': 'T', 'ECC': 'Q', 'EDA': 'A', 'EFC': 'C', 'EHP': 'F', 'EIT': 'T',
      'ENP': 'N', 'ESB': 'Y', 'ESC': 'M', 'EXB': 'X', 'EXY': 'L', 'EYS': 'X', 'F2F': 'F', 'F4Q': 'G', 'F6N': 'X',
      'F75': 'X', 'F7H': 'C', 'F7K': 'G', 'F7Q': 'Y', 'F7W': 'W', 'FA2': 'A', 'FA5': 'N', 'FAG': 'N', 'FAI': 'N',
      'FAK': 'K', 'FB5': 'A', 'FB6': 'A', 'FC0': 'F', 'FCL': 'F', 'FF9': 'K', 'FFD': 'N', 'FGA': 'E', 'FGL': 'G',
      'FGP': 'S', 'FH7': 'K', 'FHE': 'X', 'FHL': 'K', 'FHO': 'K', 'FHU': 'U', 'FLA': 'A', 'FLE': 'L', 'FLT': 'Y',
      'FME': 'M', 'FMG': 'G', 'FMU': 'N', 'FOE': 'C', 'FOX': 'G', 'FP9': 'P', 'FPK': 'P', 'FRD': 'X', 'FT6': 'W',
      'FTR': 'W', 'FTY': 'Y', 'FVA': 'V', 'FZN': 'K', 'G  ': 'G', 'G25': 'G', 'G2L': 'G', 'G2S': 'G', 'G31': 'G',
      'G32': 'G', 'G33': 'G', 'G36': 'G', 'G38': 'G', 'G42': 'G', 'G46': 'G', 'G47': 'G', 'G48': 'G', 'G49': 'G',
      'G4P': 'N', 'G7M': 'G', 'GAO': 'G', 'GAU': 'E', 'GCK': 'C', 'GCM': 'X', 'GDP': 'G', 'GDR': 'G', 'GFL': 'G',
      'GFT': 'S', 'GGL': 'E', 'GH3': 'G', 'GHG': 'Q', 'GHP': 'G', 'GL3': 'G', 'GLH': 'Q', 'GLJ': 'E', 'GLK': 'E',
      'GLM': 'X', 'GLN': 'Q', 'GLQ': 'E', 'GLU': 'E', 'GLX': 'Z', 'GLY': 'G', 'GLZ': 'G', 'GMA': 'E', 'GMS': 'G',
      'GMU': 'U', 'GN7': 'G', 'GND': 'X', 'GNE': 'N', 'GOM': 'G', 'GPL': 'K', 'GS ': 'G', 'GSC': 'G', 'GSR': 'G',
      'GSS': 'G', 'GSU': 'E', 'GT9': 'C', 'GTP': 'G', 'GVL': 'S', 'GYC': 'X', 'GYS': 'X', 'H14': 'F', 'H2U': 'U',
      'H5M': 'P', 'HAC': 'A', 'HAR': 'R', 'HBN': 'H', 'HCS': 'X', 'HDP': 'U', 'HEU': 'U', 'HFA': 'X', 'HGL': 'X',
      'HHI': 'H', 'HHK': 'X', 'HIA': 'H', 'HIC': 'H', 'HIP': 'H', 'HIQ': 'H', 'HIS': 'H', 'HL2': 'L', 'HL5': 'L',
      'HLU': 'L', 'HLY': 'K', 'HMR': 'R', 'HOL': 'N', 'HOO': 'H', 'HPC': 'F', 'HPE': 'F', 'HPH': 'F', 'HPQ': 'F',
      'HQA': 'A', 'HR7': 'R', 'HRG': 'R', 'HRP': 'W', 'HS8': 'H', 'HS9': 'H', 'HSE': 'S', 'HSL': 'S', 'HSO': 'H',
      'HSV': 'H', 'HT7': 'W', 'HTI': 'C', 'HTN': 'N', 'HTR': 'W', 'HVU': 'X', 'HV5': 'A', 'HVA': 'V', 'HY3': 'P', 'HYP': 'P',
      'HZP': 'P', 'I  ': 'I', 'I1C': 'X', 'I2M': 'I', 'I4U': 'U', 'I58': 'K', 'I5C': 'C', 'IAM': 'A', 'IAR': 'R',
      'IAS': 'D', 'IC ': 'C', 'IEL': 'K', 'IEY': 'X', 'IG ': 'G', 'IGL': 'G', 'IGU': 'G', 'IIC': 'X', 'IIL': 'I',
      'ILE': 'I', 'ILG': 'E', 'ILX': 'I', 'IMC': 'C', 'IML': 'I', 'IOY': 'F', 'IPG': 'G', 'IPN': 'N', 'IRN': 'N',
      'IT1': 'K', 'IU ': 'U', 'IYR': 'Y', 'IYT': 'T', 'IZO': 'M', 'J8W': 'S', 'JJJ': 'C', 'JJK': 'C', 'JJL': 'C',
      'JKH': 'P', 'JLP': 'K', 'JMH': 'C', 'JW5': 'N', 'K1R': 'C', 'K5H': 'C', 'K5L': 'S', 'KAG': 'G', 'KAK': 'G',
      'KCX': 'K', 'KEO': 'K', 'KGC': 'K', 'KNB': 'A', 'KOR': 'M', 'KPF': 'K', 'KPI': 'K', 'KPY': 'K', 'KST': 'K',
      'KYN': 'W', 'KYQ': 'K', 'L2A': 'X', 'L3O': 'L', 'LA2': 'K', 'LAA': 'D', 'LAL': 'A', 'LAY': 'L', 'LBY': 'K',
      'LC ': 'C', 'LCA': 'A', 'LCC': 'N', 'LCG': 'G', 'LCH': 'N', 'LCK': 'K', 'LCX': 'K', 'LCZ': 'X', 'LDH': 'K',
      'LED': 'L', 'LEF': 'L', 'LEH': 'L', 'LEI': 'V', 'LEM': 'L', 'LEN': 'L', 'LET': 'K', 'LEU': 'L', 'LEX': 'L',
      'LG ': 'G', 'LGP': 'G', 'LHC': 'X', 'LHH': 'C', 'LHU': 'U', 'LHV': 'X', 'LKC': 'N', 'LLP': 'K', 'LLY': 'K',
      'LME': 'E', 'LMF': 'K', 'LMQ': 'Q', 'LMS': 'N', 'LP6': 'K', 'LPD': 'P', 'LPG': 'G', 'LPL': 'X', 'LPS': 'S',
      'LSO': 'K', 'LTA': 'X', 'LTR': 'W', 'LV2': 'C', 'LVG': 'G', 'LVN': 'V', 'LYF': 'K', 'LYK': 'K', 'LYM': 'K',
      'LYN': 'K', 'LYO': 'K', 'LYR': 'K', 'LYS': 'K', 'LYX': 'K', 'LYZ': 'K', 'M0H': 'C', 'M1G': 'G', 'M2G': 'G',
      'M2L': 'K', 'M2S': 'M', 'M30': 'G', 'M3L': 'K', 'M5M': 'C', 'M7A': 'A', 'MA ': 'A', 'MA6': 'A', 'MA7': 'A',
      'MAA': 'A', 'MAD': 'A', 'MAI': 'R', 'MBQ': 'Y', 'MBZ': 'N', 'MC1': 'S', 'MCG': 'X', 'MCL': 'K', 'MCS': 'C',
      'MCY': 'C', 'MD3': 'C', 'MD6': 'G', 'MDF': 'Y', 'MDH': 'X', 'MDO': 'X', 'MDR': 'N', 'MEA': 'F', 'MED': 'M',
      'MEG': 'E', 'MEN': 'N', 'MEP': 'U', 'MEQ': 'Q', 'MET': 'M', 'MEU': 'G', 'MF3': 'X', 'MFC': 'X', 'MFO': 'G',
      'MFV': 'X', 'MG1': 'G', 'MGG': 'R', 'MGN': 'Q', 'MGQ': 'A', 'MGV': 'G', 'MGY': 'G', 'MH6': 'S', 'MHG': 'G',
      'MHL': 'L', 'MHO': 'M', 'MHS': 'H', 'MHU': 'F', 'MHY': 'X', 'MIA': 'A', 'MIS': 'S', 'MJ1': 'X', 'MK8': 'L',
      'ML3': 'K', 'MLE': 'L', 'MLL': 'L', 'MLY': 'K', 'MLZ': 'K', 'MME': 'M', 'MMO': 'R', 'MMT': 'T', 'MND': 'N',
      'MNL': 'L', 'MNU': 'U', 'MNV': 'V', 'MOD': 'X', 'MP8': 'P', 'MPH': 'X', 'MPJ': 'X', 'MPQ': 'G', 'MRG': 'G',
      'MSA': 'G', 'MSE': 'M', 'MSL': 'M', 'MSO': 'M', 'MSP': 'X', 'MT2': 'M', 'MTR': 'T', 'MTU': 'A', 'MTY': 'Y',
      'MVA': 'V', 'N  ': 'N', 'N10': 'S', 'N2C': 'X', 'N5I': 'N', 'N5M': 'C', 'N65': 'K', 'N6G': 'G', 'N79': 'A',
      'N7P': 'P', 'N80': 'P', 'N8P': 'P', 'NA8': 'A', 'NAL': 'A', 'NAM': 'A', 'NB8': 'N', 'NBQ': 'Y', 'NC1': 'S',
      'NCB': 'A', 'NCX': 'N', 'NCY': 'X', 'NDF': 'F', 'NDN': 'U', 'NDU': 'U', 'NEM': 'H', 'NEP': 'H', 'NF2': 'N',
      'NFA': 'F', 'NHL': 'E', 'NIT': 'X', 'NIY': 'Y', 'NLE': 'L', 'NLN': 'L', 'NLO': 'L', 'NLP': 'L', 'NLQ': 'Q',
      'NLW': 'L', 'NMC': 'G', 'NMM': 'R', 'NMS': 'T', 'NMT': 'T', 'NNH': 'R', 'NP3': 'N', 'NPH': 'C', 'NPI': 'A',
      'NRP': 'X', 'NRQ': 'X', 'NSK': 'X', 'NTR': 'Y', 'NTY': 'Y', 'NVA': 'V', 'NYB': 'C', 'NYC': 'X', 'NYG': 'X',
      'NYM': 'N', 'NYS': 'C', 'NZC': 'T', 'NZH': 'H', 'O12': 'X', 'O2C': 'N', 'O2G': 'G', 'O2Z': 'A', 'OAD': 'N',
      'OAR': 'R', 'OAS': 'S', 'OBF': 'X', 'OBS': 'K', 'OCS': 'C', 'OCY': 'C', 'ODP': 'N', 'OHD': 'X', 'OHI': 'H',
      'OHS': 'D', 'OIC': 'X', 'OIP': 'I', 'OKN': 'C', 'OKQ': 'C', 'OKT': 'U', 'OLE': 'X', 'OLT': 'T', 'OLZ': 'S',
      'OMC': 'C', 'OMG': 'G', 'OMT': 'M', 'OMU': 'U', 'OMX': 'Y', 'OMY': 'Y', 'ONE': 'U', 'ONH': 'A', 'ONL': 'X',
      'OPR': 'R', 'ORN': 'A', 'ORQ': 'R', 'OSE': 'S', 'OTB': 'X', 'OTH': 'T', 'OTZ': 'X', 'OXX': 'D', 'OZW': 'F',
      'P  ': 'G', 'P1L': 'C', 'P1P': 'N', 'P2T': 'T', 'P2U': 'U', 'P2Y': 'P', 'P4U': 'U', 'P5P': 'A', 'P7G': 'G',
      'P9S': 'C', 'PAQ': 'Y', 'PAS': 'D', 'PAT': 'W', 'PAU': 'A', 'PBB': 'C', 'PBF': 'F', 'PBT': 'N', 'PCA': 'Q',
      'PCC': 'P', 'PCE': 'X', 'PCS': 'F', 'PDL': 'X', 'PDU': 'U', 'PE1': 'K', 'PEC': 'C', 'PF5': 'F', 'PFF': 'F',
      'PFX': 'X', 'PG1': 'S', 'PG7': 'G', 'PG9': 'G', 'PGL': 'X', 'PGN': 'G', 'PGP': 'G', 'PGY': 'G', 'PH6': 'P',
      'PHA': 'F', 'PHD': 'D', 'PHE': 'F', 'PHI': 'F', 'PHL': 'F', 'PHM': 'F', 'PIA': 'X', 'PIV': 'X', 'PLE': 'L',
      'PM3': 'F', 'PLM': 'X', 'PMT': 'C', 'POK': 'R', 'POM': 'P', 'PPN': 'F', 'PPU': 'A', 'PPW': 'G', 'PQ1': 'N', 'PR3': 'C',
      'PR5': 'A', 'PR9': 'P', 'PRN': 'A', 'PRO': 'P', 'PRS': 'P', 'PRV': 'G', 'PSA': 'F', 'PSH': 'H', 'PST': 'T',
      'PSU': 'U', 'PSW': 'U', 'PTA': 'X', 'PTH': 'Y', 'PTM': 'Y', 'PTR': 'Y', 'PU ': 'A', 'PUY': 'N', 'PVH': 'H',
      'PVL': 'X', 'PYA': 'A', 'PYL': 'O', 'PYO': 'U', 'PYX': 'C', 'PYY': 'N', 'Q3P': 'K', 'QBT': 'T', 'QCS': 'C',
      'QFG': 'X', 'QLG': 'X', 'QMM': 'Q', 'QPA': 'C', 'QPH': 'F', 'QUO': 'G', 'R  ': 'A', 'R1A': 'C', 'R4K': 'W',
      'RC7': 'X', 'RE0': 'W', 'RE3': 'W', 'RFJ': 'G', 'RGL': 'R', 'RIA': 'A', 'RMP': 'A', 'RON': 'X', 'RPI': 'R',
      'RSP': 'C', 'RT ': 'T', 'RT0': 'P', 'RTP': 'N', 'RVJ': 'A', 'RVX': 'S', 'RZ4': 'S', 'S1H': 'S', 'S2C': 'C',
      'S2D': 'A', 'S2M': 'T', 'S2P': 'A', 'S4A': 'A', 'S4C': 'C', 'S4G': 'G', 'S4U': 'U', 'S6G': 'G', 'SAC': 'S',
      'SAH': 'C', 'SAR': 'G', 'SBL': 'S', 'SC ': 'C', 'SCH': 'C', 'SCS': 'C', 'SCY': 'C', 'SD2': 'X', 'SDB': 'S',
      'SDG': 'G', 'SDP': 'S', 'SE7': 'U', 'SEB': 'S', 'SEC': 'U', 'SEG': 'A', 'SEL': 'S', 'SEM': 'S', 'SEN': 'S',
      'SEP': 'S', 'SER': 'S', 'SET': 'S', 'SGB': 'S', 'SHC': 'C', 'SHP': 'G', 'SHR': 'K', 'SIB': 'C', 'SIC': 'X',
      'SKH': 'K', 'SLR': 'P', 'SLZ': 'K', 'SMC': 'C', 'SME': 'M', 'SMF': 'F', 'SMP': 'A', 'SMT': 'T', 'SNC': 'C',
      'SNM': 'S', 'SNN': 'N', 'SOC': 'U', 'SOS': 'N', 'SOY': 'S', 'SPT': 'T', 'SRA': 'A', 'SRO': 'X', 'SRZ': 'S', 'SSU': 'U',
      'STY': 'Y', 'SUB': 'X', 'SUI': 'X', 'SUN': 'S', 'SUR': 'U', 'SVA': 'S', 'SVV': 'S', 'SVW': 'S', 'SVX': 'S',
      'SVY': 'S', 'SVZ': 'S', 'SWG': 'X', 'SXE': 'S', 'SYS': 'U', 'T  ': 'T', 'T0I': 'Y', 'T11': 'F', 'T23': 'T',
      'T2S': 'T', 'T2T': 'N', 'T31': 'U', 'T32': 'T', 'T36': 'T', 'T37': 'T', 'T38': 'T', 'T39': 'T', 'T3P': 'T',
      'T41': 'T', 'T48': 'T', 'T49': 'T', 'T4S': 'T', 'T5O': 'U', 'T5S': 'T', 'T66': 'X', 'T6A': 'A', 'T8L': 'T',
      'T9E': 'T', 'TA3': 'T', 'TA4': 'X', 'TAF': 'T', 'TAL': 'N', 'TAV': 'D', 'TBG': 'V', 'TBM': 'T', 'TC1': 'C',
      'TCJ': 'C', 'TCP': 'T', 'TCQ': 'Y', 'TCR': 'W', 'TCY': 'A', 'TDD': 'L', 'TDY': 'T', 'TFE': 'T', 'TFO': 'A',
      'TFQ': 'F', 'TFT': 'T', 'TGH': 'W', 'TGP': 'G', 'TH5': 'T', 'TH6': 'T', 'THC': 'T', 'THO': 'X', 'THR': 'T',
      'THX': 'N', 'THZ': 'R', 'TIH': 'A', 'TLB': 'N', 'TLC': 'T', 'TLN': 'U', 'TMB': 'T', 'TMD': 'T', 'TNB': 'C',
      'TNR': 'S', 'TOQ': 'W', 'TOZ': 'X', 'TP1': 'T', 'TPC': 'C', 'TPG': 'G', 'TPH': 'X', 'TPJ': 'P', 'TPK': 'P',
      'TPL': 'W', 'TPO': 'T', 'TPQ': 'Y', 'TQI': 'W', 'TQQ': 'W', 'TQZ': 'C', 'TRF': 'W', 'TRG': 'K', 'TRN': 'W',
      'TRO': 'W', 'TRP': 'W', 'TRQ': 'W', 'TRW': 'W', 'TRX': 'W', 'TRY': 'W', 'TS ': 'N', 'TS9': 'I', 'TSP': 'T',
      'TST': 'X', 'TSY': 'C', 'TT ': 'N', 'TTD': 'T', 'TTI': 'U', 'TTM': 'T', 'TTQ': 'W', 'TTS': 'Y', 'TXY': 'Y',
      'TY1': 'Y', 'TY2': 'Y', 'TY3': 'Y', 'TY5': 'Y', 'TYB': 'Y', 'TYC': 'Y', 'TYI': 'Y', 'TYJ': 'Y', 'TYN': 'Y',
      'TYO': 'Y', 'TYQ': 'Y', 'TYR': 'Y', 'TYS': 'Y', 'TYT': 'Y', 'TYU': 'N', 'TYW': 'Y', 'TYX': 'X', 'TYY': 'Y',
      'TZB': 'X', 'TZO': 'X', 'U  ': 'U', 'U25': 'U', 'U2L': 'U', 'U2N': 'U', 'U2P': 'U', 'U31': 'U', 'U33': 'U',
      'U34': 'U', 'U36': 'U', 'U37': 'U', 'U8U': 'U', 'UAR': 'U', 'UBD': 'U', 'UCL': 'U', 'UD5': 'U', 'UDP': 'N',
      'UFP': 'N', 'UFR': 'U', 'UFT': 'U', 'UMA': 'A', 'UMP': 'U', 'UMS': 'U', 'UN1': 'X', 'UN2': 'X', 'UNK': 'X',
      'UR3': 'U', 'URD': 'U', 'US1': 'U', 'US2': 'U', 'US3': 'T', 'US5': 'U', 'USM': 'U', 'VAD': 'V', 'VAF': 'V',
      'VAL': 'V', 'VB1': 'K', 'VDL': 'X', 'VH0': 'P', 'VLL': 'X', 'VLM': 'X', 'VMS': 'X', 'VOL': 'X', 'VYA': 'X',
      'WCR': 'X', 'WLU': 'L', 'WPA': 'F', 'WRP': 'W', 'WVL': 'V', 'X  ': 'G', 'X2W': 'E', 'X4A': 'N', 'X9Q': 'X',
      'XAD': 'A', 'XAE': 'N', 'XAL': 'A', 'XAR': 'N', 'XCL': 'C', 'XCN': 'C', 'XCP': 'X', 'XCR': 'C', 'XCS': 'N',
      'XCT': 'C', 'XCY': 'C', 'XDT': 'T', 'XGA': 'N', 'XGL': 'G', 'XGR': 'G', 'XGU': 'G', 'XPL': 'O', 'XPR': 'P',
      'XSN': 'N', 'XTH': 'T', 'XTL': 'T', 'XTR': 'T', 'XTS': 'G', 'XTY': 'N', 'XUA': 'A', 'XUG': 'G', 'XX1': 'K',
      'XXY': 'X', 'XYG': 'X', 'Y  ': 'A', 'YCM': 'C', 'YG ': 'G', 'YOF': 'Y', 'YRR': 'N', 'YTH': 'T', 'YYG': 'G',
      'Z  ': 'C', 'Z01': 'A', 'ZAD': 'A', 'ZAL': 'A', 'ZBC': 'C', 'ZBU': 'U', 'ZCL': 'F', 'ZCY': 'C', 'ZDU': 'U',
      'ZFB': 'X', 'ZGU': 'G', 'ZHP': 'N', 'ZTH': 'T', 'ZU0': 'T', 'ZZD': 'C', 'ZZJ': 'A'
      }
